@startuml gameplay
skinparam Style strictuml

actor Obstacle <<abstract>>
actor Bot
actor User
actor Vehicle

package Movement {
    usecase move
    usecase steer
    usecase collide
}

package "Map creation" as mc {

    usecase "create map"
    usecase "add bot"
    usecase "add obstacle"
    usecase "edit map"
    
    usecase "delete map"
    usecase "save map"
    usecase "load map"
    
}

usecase "start simulation"
usecase "control"
usecase "plan path"
usecase "read map"

:Vehicle: -> collide
:Vehicle: -> move
:Vehicle: -> steer

:Bot: -> (plan path)
:Bot: -> (read map)

:Vehicle: -up-|> :Obstacle:
:Bot: -up-|> :Vehicle:
:User: -up-|> :Vehicle:
:User: -> (control)
:User: -> (start simulation)
(control) -.> (move): <<extends>>
:User: --> mc
@enduml

