@startuml gameplay
skinparam Style strictuml

actor Obstacle
actor Bot
actor User
actor Vehicle

package Movement {
    usecase move
    usecase steer
    usecase collide
}

package "Map creation" as mc {

    usecase "create map"
    usecase "save map"
    usecase "load map"
    usecase "add vehicle"
    usecase "add obstacle"
    usecase "delete objects"
    usecase "assign coordinates"
    usecase "assign rotation"
    usecase "change driver"

}

usecase "start simulation"
usecase "control vehicle"

:Vehicle: -> collide
:Vehicle: -> move
:Vehicle: -> steer

:Bot: -> (steer)
:Bot: -> collide
:Bot: -> move

:Vehicle: -up-|> :Obstacle:
:Bot: -up-|> :Vehicle:
:User: -up-|> :Vehicle:
:User: -> (control vehicle)
:User: -> (start simulation)
:User: -> (reset simulation)
(control vehicle) -.> (move): <<extends>>
(control vehicle) -.> (steer): <<extends>>
:User: --> mc
@enduml

